/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment5_group58;

import static assignment5_group58.StartGUI.courseList;
import java.awt.Container;
import java.io.Serializable;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author surya
 */
public class AddCourseGUI extends javax.swing.JFrame implements Serializable{

    /**
     * Creates new form AddCourseGUI
     */
    public AddCourseGUI(ArrayList<Course> courseList) {
        //initComponents(courseList);
        newinitComponents(courseList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /*
   // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreditsErrorDialog = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        ExitError1Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CourseNameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CreditsField = new javax.swing.JTextField();
        ProfField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CreateCourseButton = new javax.swing.JButton();

        CreditsErrorDialog.setMinimumSize(new java.awt.Dimension(227, 164));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Enter an integer in credits!");

        ExitError1Button.setText("OK");
        ExitError1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitError1ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CreditsErrorDialogLayout = new javax.swing.GroupLayout(CreditsErrorDialog.getContentPane());
        CreditsErrorDialog.getContentPane().setLayout(CreditsErrorDialogLayout);
        CreditsErrorDialogLayout.setHorizontalGroup(
            CreditsErrorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreditsErrorDialogLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4))
            .addGroup(CreditsErrorDialogLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(ExitError1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        CreditsErrorDialogLayout.setVerticalGroup(
            CreditsErrorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreditsErrorDialogLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(ExitError1Button))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Course");

        jLabel1.setText("Course Name :");

        jLabel2.setText("Credits :");

        ProfField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Professor in charge :");

        CreateCourseButton.setText("Create");
        CreateCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateCourseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CourseNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(CreditsField)
                    .addComponent(ProfField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addComponent(CreateCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CourseNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CreditsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProfField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(CreateCourseButton)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
*/
    private void newinitComponents(ArrayList<Course> courseList) {

        CreditsErrorDialog = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        ExitError1Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CourseNameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CreditsField = new javax.swing.JTextField();
        ProfField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CreateCourseButton = new javax.swing.JButton();

        CreditsErrorDialog.setMinimumSize(new java.awt.Dimension(227, 164));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Enter an integer in credits!");

        ExitError1Button.setText("OK");
        ExitError1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitError1ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CreditsErrorDialogLayout = new javax.swing.GroupLayout(CreditsErrorDialog.getContentPane());
        CreditsErrorDialog.getContentPane().setLayout(CreditsErrorDialogLayout);
        CreditsErrorDialogLayout.setHorizontalGroup(
            CreditsErrorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreditsErrorDialogLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4))
            .addGroup(CreditsErrorDialogLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(ExitError1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        CreditsErrorDialogLayout.setVerticalGroup(
            CreditsErrorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreditsErrorDialogLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(ExitError1Button))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Course");

        jLabel1.setText("Course Name :");

        jLabel2.setText("Credits :");

        ProfField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Professor in charge :");

        CreateCourseButton.setText("Create");
        CreateCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateCourseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CourseNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(CreditsField)
                    .addComponent(ProfField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addComponent(CreateCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CourseNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CreditsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProfField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(CreateCourseButton)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }
    private void CreateCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateCourseButtonActionPerformed
        Course newcourse = new Course();
        if(!(CourseNameField.getText().isEmpty()))
        {
            newcourse.setname(CourseNameField.getText());
        }
        else
        {
           JOptionPane.showMessageDialog(null,"Need to write course name!");
        }
        String regex = "[0-9]";
        String credits_string = CreditsField.getText();
        if(credits_string.matches(regex)){
            newcourse.setcredit(Integer.parseInt(credits_string));
        }else{
            this.CreditsErrorDialog.setLocationRelativeTo(null);
            this.CreditsErrorDialog.setVisible(true);
        }
        if(!(ProfField.getText().isEmpty()))
        {
            newcourse.setprofessor(ProfField.getText());
        }
        //TODO add handling for adding students to course
        
        //saving course and closing current tab
        if(!(CourseNameField.getText().isEmpty())&&newcourse.getcredit()!=-1)
        {
            courseList.add(newcourse);
            JOptionPane.showMessageDialog(null,"Course "+newcourse.getname()+" saved!");
            Container frame2 = CreateCourseButton.getParent();
            do 
            frame2 = frame2.getParent(); 
            while (!(this instanceof JFrame));                                      
                dispose();
        }
    }//GEN-LAST:event_CreateCourseButtonActionPerformed

    private void ProfFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProfFieldActionPerformed

    private void ExitError1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitError1ButtonActionPerformed
        this.CreditsErrorDialog.setVisible(false);
    }//GEN-LAST:event_ExitError1ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCourseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCourseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCourseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCourseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddCourseGUI acg = new AddCourseGUI(courseList);
                acg.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CourseNameField;
    private javax.swing.JButton CreateCourseButton;
    private javax.swing.JDialog CreditsErrorDialog;
    private javax.swing.JTextField CreditsField;
    private javax.swing.JButton ExitError1Button;
    private javax.swing.JTextField ProfField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
