/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment5_group58;

import java.io.FileNotFoundException;
import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.File;
import java.io.FileDescriptor;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.OutputStream;
import java.io.PrintStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author surya
 */
public class StartGUI extends javax.swing.JFrame implements Serializable {

    /**
     * Creates new form StartGUI
     */
    static ArrayList<Course> courseList = new ArrayList<Course>();
    static ArrayList<Transaction> cashbook = new ArrayList<Transaction>();
    static ArrayList<Item> itemList = new ArrayList<Item>();
    static double netIncome = 0.0;
    static double netExpenditure = 0.0;
    
    static int canDelete = 0;
    static int canEnroll = 0;
    static int canSelect = 0;
    static Item modifyItem = new Item();
    
    public StartGUI() {
        initComponents();
        redirectSystemStreamstoCred();
        System.out.println("Testing Debits area");
        //updateCreditsArea();
        redirectSystemStreamstoDeb();
        System.out.println("Testing Credits Area");
        //updateDebitsArea();
        //revert back to system streams
        revertstream();
    }
    
    //check if price is numeric
    public static boolean isNumeric(String str)  
    {  
      try  
      {  
           double d = Double.parseDouble(str);  
      }  
      catch(NumberFormatException nfe)  
      {  
        return false;  
      }  
      return true;  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPopup = new javax.swing.JFrame();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        LoginPwdError = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        OKButton = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        respubGroup = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Hometab = new javax.swing.JPanel();
        welcome = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        Acadstab = new javax.swing.JPanel();
        Coursepanel = new javax.swing.JPanel();
        AddCourse = new javax.swing.JButton();
        DelCourse = new javax.swing.JButton();
        ViewCourse = new javax.swing.JButton();
        Studentpanel = new javax.swing.JPanel();
        NewStudent = new javax.swing.JButton();
        EnrollStudent = new javax.swing.JButton();
        PrintStudent = new javax.swing.JButton();
        Evaluate = new javax.swing.JButton();
        Inventorytab = new javax.swing.JPanel();
        viewItem = new javax.swing.JButton();
        DelItem = new javax.swing.JButton();
        ModItem = new javax.swing.JButton();
        DispNum = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        itemName = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        itemLocation = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        itemPrice = new javax.swing.JTextField();
        saveItem = new javax.swing.JButton();
        Treasurytab = new javax.swing.JPanel();
        TransType = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PriceField = new javax.swing.JTextField();
        Details = new javax.swing.JScrollPane();
        DetailsArea = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        AddTrans = new javax.swing.JButton();
        Cashbooktab = new javax.swing.JPanel();
        Logspanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        DebitsArea = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        CreditsArea = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        IncField = new javax.swing.JTextField(Double.toString(netIncome));
        ExpField = new javax.swing.JTextField(Double.toString(netExpenditure));
        BalField = new javax.swing.JTextField(Double.toString(netIncome - netExpenditure));
        ResPubtab = new javax.swing.JPanel();
        ResPubPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        ResRadioButton = new javax.swing.JRadioButton();
        PubRadioButton = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        respubTitle = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        respubAuthority = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        respubDetails = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        respubInvestment = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        respubProfit = new javax.swing.JTextField();
        saveRespub = new javax.swing.JButton();
        ViewResearchButton = new javax.swing.JButton();
        ViewPublicationButton = new javax.swing.JButton();
        Searchtab = new javax.swing.JPanel();
        SearchField = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        SearchResTable = new javax.swing.JTable();

        LoginPopup.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        LoginPopup.setTitle("Login Page");
        LoginPopup.setMinimumSize(new java.awt.Dimension(240, 127));
        LoginPopup.setResizable(false);

        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Password:");

        jLabel3.setText("Login to UDIS");

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginPopupLayout = new javax.swing.GroupLayout(LoginPopup.getContentPane());
        LoginPopup.getContentPane().setLayout(LoginPopupLayout);
        LoginPopupLayout.setHorizontalGroup(
            LoginPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPopupLayout.createSequentialGroup()
                .addGroup(LoginPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPopupLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginPopupLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel3))
                    .addGroup(LoginPopupLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jButton1)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        LoginPopupLayout.setVerticalGroup(
            LoginPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPopupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(LoginPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );

        LoginPwdError.setTitle("Password Error");
        LoginPwdError.setLocation(new java.awt.Point(0, 0));
        LoginPwdError.setMinimumSize(new java.awt.Dimension(184, 140));
        LoginPwdError.setResizable(false);

        jLabel1.setText("Incorrect Password Entered");

        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginPwdErrorLayout = new javax.swing.GroupLayout(LoginPwdError.getContentPane());
        LoginPwdError.getContentPane().setLayout(LoginPwdErrorLayout);
        LoginPwdErrorLayout.setHorizontalGroup(
            LoginPwdErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPwdErrorLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1))
            .addGroup(LoginPwdErrorLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(OKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        LoginPwdErrorLayout.setVerticalGroup(
            LoginPwdErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPwdErrorLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(OKButton)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        welcome.setText("Welcome to IIT KGP Department Information System");

        time.setText("time");

        date.setText("date");

        javax.swing.GroupLayout HometabLayout = new javax.swing.GroupLayout(Hometab);
        Hometab.setLayout(HometabLayout);
        HometabLayout.setHorizontalGroup(
            HometabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HometabLayout.createSequentialGroup()
                .addGap(0, 38, Short.MAX_VALUE)
                .addGroup(HometabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(welcome)
                    .addComponent(date))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(time))
        );
        HometabLayout.setVerticalGroup(
            HometabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HometabLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(welcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addGroup(HometabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(time)
                    .addComponent(date)))
        );

        jTabbedPane1.addTab("Home", Hometab);

        Coursepanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Course"));
        Coursepanel.setToolTipText("Course1");
        Coursepanel.setFont(Coursepanel.getFont().deriveFont(Coursepanel.getFont().getStyle() | java.awt.Font.BOLD));
        Coursepanel.setName("Course"); // NOI18N

        AddCourse.setText("Add Course");
        AddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCourseActionPerformed(evt);
            }
        });

        DelCourse.setText("Delete Course");
        DelCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelCourseActionPerformed(evt);
            }
        });

        ViewCourse.setText("View Course");
        ViewCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CoursepanelLayout = new javax.swing.GroupLayout(Coursepanel);
        Coursepanel.setLayout(CoursepanelLayout);
        CoursepanelLayout.setHorizontalGroup(
            CoursepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoursepanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(CoursepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DelCourse)
                    .addComponent(AddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        CoursepanelLayout.setVerticalGroup(
            CoursepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoursepanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(AddCourse)
                .addGap(18, 18, 18)
                .addComponent(DelCourse)
                .addGap(18, 18, 18)
                .addComponent(ViewCourse)
                .addGap(30, 30, 30))
        );

        Studentpanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Student"));

        NewStudent.setText("New Student");
        NewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewStudentActionPerformed(evt);
            }
        });

        EnrollStudent.setText("Enroll Student");
        EnrollStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnrollStudentActionPerformed(evt);
            }
        });

        PrintStudent.setText("Print Student");

        javax.swing.GroupLayout StudentpanelLayout = new javax.swing.GroupLayout(Studentpanel);
        Studentpanel.setLayout(StudentpanelLayout);
        StudentpanelLayout.setHorizontalGroup(
            StudentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentpanelLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(StudentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EnrollStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NewStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PrintStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(66, 66, 66))
        );
        StudentpanelLayout.setVerticalGroup(
            StudentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NewStudent)
                .addGap(18, 18, 18)
                .addComponent(EnrollStudent)
                .addGap(18, 18, 18)
                .addComponent(PrintStudent)
                .addGap(32, 32, 32))
        );

        Evaluate.setText("Enter Credits");
        Evaluate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvaluateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AcadstabLayout = new javax.swing.GroupLayout(Acadstab);
        Acadstab.setLayout(AcadstabLayout);
        AcadstabLayout.setHorizontalGroup(
            AcadstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AcadstabLayout.createSequentialGroup()
                .addGroup(AcadstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AcadstabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Coursepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Studentpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AcadstabLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(Evaluate, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AcadstabLayout.setVerticalGroup(
            AcadstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AcadstabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AcadstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Coursepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Studentpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(Evaluate)
                .addGap(31, 31, 31))
        );

        jTabbedPane1.addTab("Academics", Acadstab);

        viewItem.setText("View all");
        viewItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewItemActionPerformed(evt);
            }
        });

        DelItem.setText("Delete Item");
        DelItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelItemActionPerformed(evt);
            }
        });

        ModItem.setText("Modify Details");
        ModItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModItemActionPerformed(evt);
            }
        });

        DispNum.setText("Display by Numbers");
        DispNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DispNumActionPerformed(evt);
            }
        });

        jLabel12.setText("Name : ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("New item");

        jLabel14.setText("Location :");

        jLabel15.setText("Price : ");

        itemPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPriceActionPerformed(evt);
            }
        });

        saveItem.setText("Save");
        saveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel12)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemName)
                    .addComponent(itemLocation)
                    .addComponent(itemPrice)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(saveItem, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(itemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(itemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(saveItem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout InventorytabLayout = new javax.swing.GroupLayout(Inventorytab);
        Inventorytab.setLayout(InventorytabLayout);
        InventorytabLayout.setHorizontalGroup(
            InventorytabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventorytabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(InventorytabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(DelItem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DispNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewItem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        InventorytabLayout.setVerticalGroup(
            InventorytabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventorytabLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(viewItem)
                .addGap(18, 18, 18)
                .addComponent(DelItem)
                .addGap(18, 18, 18)
                .addComponent(ModItem)
                .addGap(29, 29, 29)
                .addComponent(DispNum)
                .addGap(63, 63, 63))
            .addGroup(InventorytabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Inventory", Inventorytab);

        TransType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grant", "Fund", "Non Inventory Expenture" }));
        TransType.setToolTipText("Select a transaction type");
        TransType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransTypeActionPerformed(evt);
            }
        });

        jLabel4.setText("Transaction Type:");

        jLabel5.setText("Price:");

        DetailsArea.setColumns(20);
        DetailsArea.setRows(5);
        Details.setViewportView(DetailsArea);

        jLabel6.setText("Details:");

        AddTrans.setText("Add Transaction");
        AddTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTransActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TreasurytabLayout = new javax.swing.GroupLayout(Treasurytab);
        Treasurytab.setLayout(TreasurytabLayout);
        TreasurytabLayout.setHorizontalGroup(
            TreasurytabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TreasurytabLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(TreasurytabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(35, 35, 35)
                .addGroup(TreasurytabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddTrans)
                    .addComponent(Details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TreasurytabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TransType, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PriceField)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        TreasurytabLayout.setVerticalGroup(
            TreasurytabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TreasurytabLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(TreasurytabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TransType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TreasurytabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(PriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TreasurytabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(AddTrans)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Treasury", Treasurytab);

        Logspanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Logs"));

        jLabel10.setText("Debit");

        DebitsArea.setColumns(20);
        DebitsArea.setRows(5);
        jScrollPane4.setViewportView(DebitsArea);

        CreditsArea.setColumns(20);
        CreditsArea.setRows(5);
        jScrollPane5.setViewportView(CreditsArea);

        jLabel11.setText("Credit");

        javax.swing.GroupLayout LogspanelLayout = new javax.swing.GroupLayout(Logspanel);
        Logspanel.setLayout(LogspanelLayout);
        LogspanelLayout.setHorizontalGroup(
            LogspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogspanelLayout.createSequentialGroup()
                .addGroup(LogspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LogspanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel10))
                    .addGroup(LogspanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(LogspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogspanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogspanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(179, 179, 179))))
        );
        LogspanelLayout.setVerticalGroup(
            LogspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogspanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LogspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LogspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(jScrollPane5))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel7.setText("Income :");

        jLabel8.setText("Expenditure :");

        jLabel9.setText("Balance :");

        javax.swing.GroupLayout CashbooktabLayout = new javax.swing.GroupLayout(Cashbooktab);
        Cashbooktab.setLayout(CashbooktabLayout);
        CashbooktabLayout.setHorizontalGroup(
            CashbooktabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CashbooktabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logspanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(CashbooktabLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(CashbooktabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CashbooktabLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BalField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CashbooktabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(CashbooktabLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(ExpField))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CashbooktabLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(IncField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CashbooktabLayout.setVerticalGroup(
            CashbooktabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CashbooktabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CashbooktabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(IncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CashbooktabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ExpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CashbooktabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(BalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Logspanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cash book", Cashbooktab);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Research / Publication");

        respubGroup.add(ResRadioButton);
        ResRadioButton.setSelected(true);
        ResRadioButton.setText("Research");

        respubGroup.add(PubRadioButton);
        PubRadioButton.setText("Publication");

        jLabel17.setText("Title :");

        jLabel18.setText("In-charge :");

        jLabel19.setText("Details :");

        respubDetails.setColumns(20);
        respubDetails.setRows(5);
        jScrollPane1.setViewportView(respubDetails);

        jLabel20.setText("Investment :");

        jLabel21.setText("Profit :");

        saveRespub.setText("Save");
        saveRespub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveRespubActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ResPubPanelLayout = new javax.swing.GroupLayout(ResPubPanel);
        ResPubPanel.setLayout(ResPubPanelLayout);
        ResPubPanelLayout.setHorizontalGroup(
            ResPubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResPubPanelLayout.createSequentialGroup()
                .addGroup(ResPubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ResPubPanelLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ResPubPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(ResPubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ResPubPanelLayout.createSequentialGroup()
                                .addComponent(ResRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(PubRadioButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(ResPubPanelLayout.createSequentialGroup()
                                .addGroup(ResPubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addGroup(ResPubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel21))
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ResPubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(respubTitle)
                                    .addComponent(respubAuthority)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                    .addComponent(respubInvestment)
                                    .addComponent(respubProfit)
                                    .addGroup(ResPubPanelLayout.createSequentialGroup()
                                        .addComponent(saveRespub, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addGap(27, 27, 27))
        );
        ResPubPanelLayout.setVerticalGroup(
            ResPubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResPubPanelLayout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ResPubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PubRadioButton)
                    .addComponent(ResRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ResPubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(respubTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ResPubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(respubAuthority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ResPubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ResPubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(respubInvestment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ResPubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(respubProfit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveRespub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        ViewResearchButton.setText("View Research");
        ViewResearchButton.setMaximumSize(new java.awt.Dimension(105, 25));
        ViewResearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewResearchButtonActionPerformed(evt);
            }
        });

        ViewPublicationButton.setText("View Publication");
        ViewPublicationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPublicationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ResPubtabLayout = new javax.swing.GroupLayout(ResPubtab);
        ResPubtab.setLayout(ResPubtabLayout);
        ResPubtabLayout.setHorizontalGroup(
            ResPubtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResPubtabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ResPubPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(ResPubtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ViewResearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ViewPublicationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        ResPubtabLayout.setVerticalGroup(
            ResPubtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ResPubPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ResPubtabLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(ViewResearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(ViewPublicationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Research/Publication", ResPubtab);

        SearchField.setText("Enter Search ");

        SearchResTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Author", "Expenditure", "Details"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(SearchResTable);
        if (SearchResTable.getColumnModel().getColumnCount() > 0) {
            SearchResTable.getColumnModel().getColumn(0).setResizable(false);
            SearchResTable.getColumnModel().getColumn(1).setResizable(false);
            SearchResTable.getColumnModel().getColumn(2).setResizable(false);
            SearchResTable.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout SearchtabLayout = new javax.swing.GroupLayout(Searchtab);
        Searchtab.setLayout(SearchtabLayout);
        SearchtabLayout.setHorizontalGroup(
            SearchtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchtabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SearchtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchField)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE))
                .addContainerGap())
        );
        SearchtabLayout.setVerticalGroup(
            SearchtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchtabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Search", Searchtab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateDebitsTextArea(final String text) {
    SwingUtilities.invokeLater(() -> {
        DebitsArea.append(text);
    });
    }
    
    private void updateCreditsTextArea(final String text) {
    SwingUtilities.invokeLater(() -> {
        CreditsArea.append(text);
    });
    }
    
    private void redirectSystemStreamstoDeb() {
    OutputStream out;
        out = new OutputStream() {
            @Override
            public void write(int b) throws IOException {
                updateDebitsTextArea(String.valueOf((char) b));
            }
            
            @Override
            public void write(byte[] b, int off, int len) throws IOException {
                updateDebitsTextArea(new String(b, off, len));
            }
            
            @Override
            public void write(byte[] b) throws IOException {
                write(b, 0, b.length);
            }
        };
 
    System.setOut(new PrintStream(out, true));
    System.setErr(new PrintStream(out, true));
    }
    
    private void redirectSystemStreamstoCred() {
    OutputStream out;
        out = new OutputStream() {
            @Override
            public void write(int b) throws IOException {
                updateCreditsTextArea(String.valueOf((char) b));
            }
            
            @Override
            public void write(byte[] b, int off, int len) throws IOException {
                updateCreditsTextArea(new String(b, off, len));
            }
            
            @Override
            public void write(byte[] b) throws IOException {
                write(b, 0, b.length);
            }
        };
 
    System.setOut(new PrintStream(out, true));
    System.setErr(new PrintStream(out, true));
    }
    
    //revert system streams
    
    private void revertstream(){
        System.setOut(new PrintStream(new FileOutputStream(FileDescriptor.out)));
    }
    
    //updating debits area
    private void updateDebitsArea(){
        DebitsArea.setText("");
        
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String pwd = new String(this.jPasswordField1.getPassword());
        if (pwd.equals("")) {  //security threat !!                  
            this.LoginPopup.setVisible(false);
            this.setVisible(true);
            Date d = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");
            this.time.setText(sdf.format(d));
            SimpleDateFormat sdf1 = new SimpleDateFormat("dd-MM-yyyy");
            this.date.setText(sdf1.format(d));
        } else {
            this.LoginPwdError.setLocationRelativeTo(null);
            this.LoginPwdError.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        String pwd = new String(this.jPasswordField1.getPassword());
        if (pwd.equals("")) {      //security threat !!              
            this.LoginPopup.setVisible(false);
            this.setVisible(true);
            Date d = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");
            this.time.setText(sdf.format(d));
            SimpleDateFormat sdf1 = new SimpleDateFormat("dd-MM-yyyy");
            this.date.setText(sdf1.format(d));
        } else {
            this.LoginPwdError.setLocationRelativeTo(null);
            this.LoginPwdError.setVisible(true);
        }
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void TransTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TransTypeActionPerformed

    private void AddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCourseActionPerformed
        AddCourseGUI newcoursegui;
        //todo : add exceptions here
        //try {
        newcoursegui = new AddCourseGUI(courseList);
        newcoursegui.setLocationRelativeTo(null);
        newcoursegui.setVisible(true);
        //optional 
        //setVisible(false);
        /*} catch (FileNotFoundException ex) {
            Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_AddCourseActionPerformed

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        this.LoginPwdError.setVisible(false);
    }//GEN-LAST:event_OKButtonActionPerformed

    private void DelCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelCourseActionPerformed
        ViewAndDeleteCourseGUI coursegui;
        //todo : add exceptions here
        //try {
        canDelete = 1;
        canEnroll = 0;
        canSelect = 0;
        coursegui = new ViewAndDeleteCourseGUI(courseList,canDelete,canEnroll, canSelect);
        coursegui.setLocationRelativeTo(null);
        coursegui.setVisible(true);
        //optional
        //setVisible(false);
        /*} catch (FileNotFoundException ex) {
            Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_DelCourseActionPerformed

    private void ViewCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewCourseActionPerformed
        ViewAndDeleteCourseGUI coursegui;
        //todo : add exceptions here
        //try {
        canDelete = 0;
        canEnroll = 0;
        canSelect = 0;
        coursegui = new ViewAndDeleteCourseGUI(courseList, canDelete, canEnroll, canSelect);
        coursegui.setLocationRelativeTo(null);
        coursegui.setVisible(true);
        //optional
        //setVisible(false);
        /*} catch (FileNotFoundException ex) {
            Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_ViewCourseActionPerformed

    private void EvaluateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvaluateActionPerformed
        ViewAndDeleteCourseGUI newviewcoursegui;
        //todo : add exceptions here
        //try {
        canDelete = 0;
        canEnroll = 0;
        canSelect = 1;
        newviewcoursegui = new ViewAndDeleteCourseGUI(courseList, canDelete, canEnroll, canSelect);
        newviewcoursegui.setLocationRelativeTo(null);
        newviewcoursegui.setVisible(true);
        //optional 
        //setVisible(false);
        /*} catch (FileNotFoundException ex) {
            Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_EvaluateActionPerformed

    private void NewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewStudentActionPerformed
        AddStudentGUI newgui;
        //todo : add exceptions here
        //try {
        newgui = new AddStudentGUI();
        newgui.setLocationRelativeTo(null);
        newgui.setVisible(true);
        //optional 
        //setVisible(false);
        /*} catch (FileNotFoundException ex) {
            Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_NewStudentActionPerformed

    private void AddTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTransActionPerformed
        // TODO add your handling code here:
        Transaction newTransaction = new Transaction();
        String selected = (String) TransType.getSelectedItem();
      
        //  JOptionPane.showMessageDialog(null,"Type : "+selected);
        newTransaction.settitle(selected);
        newTransaction.setauthority("");
        newTransaction.settype(selected);
        newTransaction.setdetails(DetailsArea.getText());
        
        if(PriceField.getText().isEmpty()||!isNumeric(PriceField.getText())){
             JOptionPane.showMessageDialog(null, "Need to enter price correctly !");
        }
        else
        {
            if(selected.equals("Non Inventory Expenture"))
            {
                newTransaction.setprofit(0.0);
                newTransaction.setinvestment(Double.parseDouble(PriceField.getText()));
            }
            else
            {
                newTransaction.setinvestment(0.0);
                newTransaction.setprofit(Double.parseDouble(PriceField.getText()));
            }
            //transaction must be saved
            netIncome += newTransaction.getprofit();
            netExpenditure += newTransaction.getinvestment();
            cashbook.add(newTransaction);
            
           // JOptionPane.showMessageDialog(null,"Type : "+selected+" profit "
           //+newTransaction.getprofit()+" invest "+newTransaction.getinvestment());
           JOptionPane.showMessageDialog(null, "Current income = "+netIncome+
                   "\nCurrent expenditure : "+netExpenditure+
                   "\nCurrent balance : "+(netIncome - netExpenditure));
           
           if(netIncome < netExpenditure)
           {
               JOptionPane.showMessageDialog(null,"Negative balance! Suggested to add grant/fund");
           }
           //update incfiels and expfield
           IncField.setText(Double.toString(netIncome));
           ExpField.setText(Double.toString(netExpenditure));
           BalField.setText(Double.toString(netIncome - netExpenditure));
        }
    }//GEN-LAST:event_AddTransActionPerformed

    private void saveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveItemActionPerformed
        // TODO add your handling code here:
        Item newItem = new Item();
        Transaction itemTrans = new Transaction();
        
        if(itemName.getText().isEmpty())
       {
            JOptionPane.showMessageDialog(null,"Need to enter name!");
        }
        else if(itemLocation.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Need to enter location!");
        }
        else if(itemPrice.getText().isEmpty()||!isNumeric(itemPrice.getText()))
        {
            JOptionPane.showMessageDialog(null,"Need to enter price correctly!");
        }
        else//non are empty
        {
            newItem.setname(itemName.getText());
            newItem.setlocation(itemLocation.getText());
            newItem.setprice(Double.parseDouble(itemPrice.getText()));
            itemList.add(newItem);
            JOptionPane.showMessageDialog(null,"Item "+newItem.getname()+" has been added!");
            
            itemTrans.settitle(newItem.getname());
            itemTrans.setauthority("Inventory");
            itemTrans.setdetails("Location :"+newItem.getlocation());
            itemTrans.setinvestment(newItem.getprice());
            itemTrans.setprofit(0.0);
            itemTrans.settype("Item");
            
            netExpenditure += itemTrans.getinvestment();
            cashbook.add(itemTrans);
            JOptionPane.showMessageDialog(null, "Current income = "+netIncome+
                   "\nCurrent expenditure : "+netExpenditure+
                   "\nCurrent balance : "+(netIncome - netExpenditure));
           
           if(netIncome < netExpenditure)
           {
               JOptionPane.showMessageDialog(null,"Negative balance! Suggested to add grant/fund");
           }
           
           //update incfiels and expfield
           IncField.setText(Double.toString(netIncome));
           ExpField.setText(Double.toString(netExpenditure));
           BalField.setText(Double.toString(netIncome - netExpenditure));
        }
    }//GEN-LAST:event_saveItemActionPerformed

    private void viewItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewItemActionPerformed
        // TODO add your handling code here:
        canDelete = 0;
        ViewItemGUI newgui = new ViewItemGUI(itemList,canDelete,modifyItem);
        newgui.setLocationRelativeTo(null);
        newgui.setVisible(true);
        
    }//GEN-LAST:event_viewItemActionPerformed

    private void DelItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelItemActionPerformed
        // TODO add your handling code here:
                canDelete = 1;
        ViewItemGUI newgui = new ViewItemGUI(itemList,canDelete,modifyItem);
        newgui.setLocationRelativeTo(null);
        newgui.setVisible(true);
    }//GEN-LAST:event_DelItemActionPerformed

    private void itemPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPriceActionPerformed
        // TODO add your handling code here:
        Item newItem = new Item();
        Transaction itemTrans = new Transaction();
        
        if(itemName.getText().isEmpty())
       {
            JOptionPane.showMessageDialog(null,"Need to enter name!");
        }
        else if(itemLocation.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Need to enter location!");
        }
        else if(itemPrice.getText().isEmpty()||!isNumeric(itemPrice.getText()))
        {
            JOptionPane.showMessageDialog(null,"Need to enter price correctly!");
        }
        else//non are empty
        {
            newItem.setname(itemName.getText());
            newItem.setlocation(itemLocation.getText());
            newItem.setprice(Double.parseDouble(itemPrice.getText()));
            itemList.add(newItem);
            JOptionPane.showMessageDialog(null,"Item "+newItem.getname()+" has been added!");
            
            itemTrans.settitle(newItem.getname());
            itemTrans.setauthority("Inventory");
            itemTrans.setdetails("Location :"+newItem.getlocation());
            itemTrans.setinvestment(newItem.getprice());
            itemTrans.setprofit(0.0);
            itemTrans.settype("Item");
            
            netExpenditure += itemTrans.getinvestment();
            cashbook.add(itemTrans);
            JOptionPane.showMessageDialog(null, "Current income = "+netIncome+
                   "\nCurrent expenditure : "+netExpenditure+
                   "\nCurrent balance : "+(netIncome - netExpenditure));
           
           if(netIncome < netExpenditure)
           {
               JOptionPane.showMessageDialog(null,"Negative balance! Suggested to add grant/fund");
           }JOptionPane.showMessageDialog(null, "Current income = "+netIncome+
                   "\nCurrent expenditure : "+netExpenditure);
           
        }//update incfiels and expfield
           IncField.setText(Double.toString(netIncome));
           ExpField.setText(Double.toString(netExpenditure));
           BalField.setText(Double.toString(netIncome - netExpenditure));
    }//GEN-LAST:event_itemPriceActionPerformed

    private void ModItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModItemActionPerformed
        // TODO add your handling code here:
        canDelete = -1;
        ViewItemGUI newgui = new ViewItemGUI(itemList,canDelete,modifyItem);
        newgui.setLocationRelativeTo(null);
        newgui.setVisible(true);
        
    }//GEN-LAST:event_ModItemActionPerformed

    private void DispNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DispNumActionPerformed
        // TODO add your handling code here:
        ItemNumGUI numgui = new ItemNumGUI(itemList);
        numgui.setLocationRelativeTo(null);
        numgui.setVisible(true);
    }//GEN-LAST:event_DispNumActionPerformed

    private void saveRespubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveRespubActionPerformed
        // TODO add your handling code here:
        Transaction newResPub = new Transaction();
        if(respubTitle.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Enter name !");
        }
        else if(respubAuthority.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Enter name of in-charge !");
        }
        else if(!isNumeric(respubInvestment.getText()))
        {
            JOptionPane.showMessageDialog(null,"Enter numerical investment!- 0 if none ");
        }
        else if(!isNumeric(respubProfit.getText()))
        {
            JOptionPane.showMessageDialog(null,"Enter numerical profit!- 0 if none ");
        }
        else
        {//minimum details are present
            if(ResRadioButton.isSelected())
            {
                newResPub.settype("Research");
            }
            else
            {
                newResPub.settype("Publication");
            }
            
            newResPub.settitle(respubTitle.getText());
            newResPub.setauthority(respubAuthority.getText());
            newResPub.setdetails(respubDetails.getText());
            newResPub.setinvestment(Double.parseDouble(respubInvestment.getText()));
            newResPub.setprofit(Double.parseDouble(respubProfit.getText()));
            
            //transaction must be saved
            netIncome += newResPub.getprofit();
            netExpenditure += newResPub.getinvestment();
            cashbook.add(newResPub);
           JOptionPane.showMessageDialog(null,newResPub.gettype()+" "+newResPub.gettitle()+" added!");
           
           JOptionPane.showMessageDialog(null, "Current income = "+netIncome+
                   "\nCurrent expenditure : "+netExpenditure+
                   "\nCurrent balance : "+(netIncome - netExpenditure));
           
           if(netIncome < netExpenditure)
           {
               JOptionPane.showMessageDialog(null,"Negative balance! Suggested to add grant/fund");
           }
           //update incfiels and expfield
           IncField.setText(Double.toString(netIncome));
           ExpField.setText(Double.toString(netExpenditure));
           BalField.setText(Double.toString(netIncome - netExpenditure));
            
        }
        
    }//GEN-LAST:event_saveRespubActionPerformed

    private void ViewResearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewResearchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewResearchButtonActionPerformed

    private void ViewPublicationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPublicationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewPublicationButtonActionPerformed

    private void EnrollStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnrollStudentActionPerformed
        ViewAndDeleteCourseGUI newgui;
        //todo : add exceptions here
        //try {
        canDelete = 0;
        canEnroll = 1;
        canSelect = 0;
        newgui = new ViewAndDeleteCourseGUI(courseList, canDelete, canEnroll, canSelect);
        newgui.setLocationRelativeTo(null);
        newgui.setVisible(true);
        //optional 
        //setVisible(false);
        /*} catch (FileNotFoundException ex) {
            Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_EnrollStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    //javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    String laf = javax.swing.UIManager.getSystemLookAndFeelClassName();
                    javax.swing.UIManager.setLookAndFeel(laf);
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                StartGUI s = new StartGUI();
                s.LoginPopup.setLocationRelativeTo(null);
                s.LoginPopup.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Acadstab;
    private javax.swing.JButton AddCourse;
    private javax.swing.JButton AddTrans;
    public static javax.swing.JTextField BalField;
    private javax.swing.JPanel Cashbooktab;
    private javax.swing.JPanel Coursepanel;
    private javax.swing.JTextArea CreditsArea;
    private javax.swing.JTextArea DebitsArea;
    private javax.swing.JButton DelCourse;
    private javax.swing.JButton DelItem;
    private javax.swing.JScrollPane Details;
    private javax.swing.JTextArea DetailsArea;
    private javax.swing.JButton DispNum;
    private javax.swing.JButton EnrollStudent;
    private javax.swing.JButton Evaluate;
    public static javax.swing.JTextField ExpField;
    private javax.swing.JPanel Hometab;
    public static javax.swing.JTextField IncField;
    private javax.swing.JPanel Inventorytab;
    private javax.swing.JFrame LoginPopup;
    private javax.swing.JDialog LoginPwdError;
    private javax.swing.JPanel Logspanel;
    private javax.swing.JButton ModItem;
    private javax.swing.JButton NewStudent;
    private javax.swing.JButton OKButton;
    private javax.swing.JTextField PriceField;
    private javax.swing.JButton PrintStudent;
    private javax.swing.JRadioButton PubRadioButton;
    private javax.swing.JPanel ResPubPanel;
    private javax.swing.JPanel ResPubtab;
    private javax.swing.JRadioButton ResRadioButton;
    private javax.swing.JTextField SearchField;
    private javax.swing.JTable SearchResTable;
    private javax.swing.JPanel Searchtab;
    private javax.swing.JPanel Studentpanel;
    private javax.swing.JComboBox<String> TransType;
    private javax.swing.JPanel Treasurytab;
    private javax.swing.JButton ViewCourse;
    private javax.swing.JButton ViewPublicationButton;
    private javax.swing.JButton ViewResearchButton;
    private javax.swing.JLabel date;
    private javax.swing.JTextField itemLocation;
    private javax.swing.JTextField itemName;
    private javax.swing.JTextField itemPrice;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField respubAuthority;
    private javax.swing.JTextArea respubDetails;
    private javax.swing.ButtonGroup respubGroup;
    private javax.swing.JTextField respubInvestment;
    private javax.swing.JTextField respubProfit;
    private javax.swing.JTextField respubTitle;
    private javax.swing.JButton saveItem;
    private javax.swing.JButton saveRespub;
    private javax.swing.JLabel sem;
    private javax.swing.JLabel time;
    private javax.swing.JButton viewItem;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
