/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment5_group58;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author surya
 */
public class StartGUI extends javax.swing.JFrame {

    /**
     * Creates new form StartGUI
     */
    public StartGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPopup = new javax.swing.JFrame();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        LoginPwdError = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        OKButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Hometab = new javax.swing.JPanel();
        welcome = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        sem = new javax.swing.JLabel();
        Acadstab = new javax.swing.JPanel();
        Coursepanel = new javax.swing.JPanel();
        AddCourse = new javax.swing.JButton();
        DelCourse = new javax.swing.JButton();
        ViewCourse = new javax.swing.JButton();
        Studentpanel = new javax.swing.JPanel();
        NewStudent = new javax.swing.JButton();
        EnrollStudent = new javax.swing.JButton();
        PrintStudent = new javax.swing.JButton();
        Evaluate = new javax.swing.JButton();
        Inventorytab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LocTable = new javax.swing.JTable();
        AddItem = new javax.swing.JButton();
        DelItem = new javax.swing.JButton();
        ModItem = new javax.swing.JButton();
        DispNum = new javax.swing.JButton();
        Treasurytab = new javax.swing.JPanel();
        TransType = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PriceField = new javax.swing.JTextField();
        Details = new javax.swing.JScrollPane();
        DetailsArea = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        AddTrans = new javax.swing.JButton();
        Cashbooktab = new javax.swing.JPanel();
        Logspanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        DebitsArea = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        CreditsArea = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        IncField = new javax.swing.JTextField();
        ExpField = new javax.swing.JTextField();
        BalField = new javax.swing.JTextField();
        ResPubtab = new javax.swing.JPanel();
        Respanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ResArea = new javax.swing.JTextArea();
        Pubpanel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        PubArea = new javax.swing.JTextArea();
        AddResPub = new javax.swing.JButton();
        Searchtab = new javax.swing.JPanel();
        SearchField = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        SearchResTable = new javax.swing.JTable();

        LoginPopup.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        LoginPopup.setTitle("Login Page");
        LoginPopup.setMinimumSize(new java.awt.Dimension(240, 127));
        LoginPopup.setResizable(false);

        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Password:");

        jLabel3.setText("Login to UDIS");

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginPopupLayout = new javax.swing.GroupLayout(LoginPopup.getContentPane());
        LoginPopup.getContentPane().setLayout(LoginPopupLayout);
        LoginPopupLayout.setHorizontalGroup(
            LoginPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPopupLayout.createSequentialGroup()
                .addGroup(LoginPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPopupLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginPopupLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel3))
                    .addGroup(LoginPopupLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jButton1)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        LoginPopupLayout.setVerticalGroup(
            LoginPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPopupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(LoginPopupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );

        LoginPwdError.setTitle("Password Error");
        LoginPwdError.setLocation(new java.awt.Point(0, 0));
        LoginPwdError.setMinimumSize(new java.awt.Dimension(184, 140));
        LoginPwdError.setResizable(false);

        jLabel1.setText("Incorrect Password Entered");

        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginPwdErrorLayout = new javax.swing.GroupLayout(LoginPwdError.getContentPane());
        LoginPwdError.getContentPane().setLayout(LoginPwdErrorLayout);
        LoginPwdErrorLayout.setHorizontalGroup(
            LoginPwdErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPwdErrorLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1))
            .addGroup(LoginPwdErrorLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(OKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        LoginPwdErrorLayout.setVerticalGroup(
            LoginPwdErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPwdErrorLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(OKButton)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        welcome.setText("Welcome to IIT KGP Department Information System");

        time.setText("time");

        date.setText("date");

        sem.setText("semester");

        javax.swing.GroupLayout HometabLayout = new javax.swing.GroupLayout(Hometab);
        Hometab.setLayout(HometabLayout);
        HometabLayout.setHorizontalGroup(
            HometabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HometabLayout.createSequentialGroup()
                .addGroup(HometabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(HometabLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(welcome))
                    .addGroup(HometabLayout.createSequentialGroup()
                        .addComponent(sem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 395, Short.MAX_VALUE)
                        .addComponent(date)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(time))
        );
        HometabLayout.setVerticalGroup(
            HometabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HometabLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(welcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addGroup(HometabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(time)
                    .addComponent(date)
                    .addComponent(sem)))
        );

        jTabbedPane1.addTab("Home", Hometab);

        Coursepanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Course"));
        Coursepanel.setToolTipText("Course1");
        Coursepanel.setFont(Coursepanel.getFont().deriveFont(Coursepanel.getFont().getStyle() | java.awt.Font.BOLD));
        Coursepanel.setName("Course"); // NOI18N

        AddCourse.setText("Add Course");
        AddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCourseActionPerformed(evt);
            }
        });

        DelCourse.setText("Delete Course");

        ViewCourse.setText("View Course");

        javax.swing.GroupLayout CoursepanelLayout = new javax.swing.GroupLayout(Coursepanel);
        Coursepanel.setLayout(CoursepanelLayout);
        CoursepanelLayout.setHorizontalGroup(
            CoursepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoursepanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(CoursepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DelCourse)
                    .addComponent(AddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        CoursepanelLayout.setVerticalGroup(
            CoursepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoursepanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(AddCourse)
                .addGap(18, 18, 18)
                .addComponent(DelCourse)
                .addGap(18, 18, 18)
                .addComponent(ViewCourse)
                .addGap(30, 30, 30))
        );

        Studentpanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Student"));

        NewStudent.setText("New Student");

        EnrollStudent.setText("Enroll Student");

        PrintStudent.setText("Print Student");

        javax.swing.GroupLayout StudentpanelLayout = new javax.swing.GroupLayout(Studentpanel);
        Studentpanel.setLayout(StudentpanelLayout);
        StudentpanelLayout.setHorizontalGroup(
            StudentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentpanelLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(StudentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EnrollStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NewStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PrintStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(66, 66, 66))
        );
        StudentpanelLayout.setVerticalGroup(
            StudentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NewStudent)
                .addGap(18, 18, 18)
                .addComponent(EnrollStudent)
                .addGap(18, 18, 18)
                .addComponent(PrintStudent)
                .addGap(32, 32, 32))
        );

        Evaluate.setText("Evaluate ");

        javax.swing.GroupLayout AcadstabLayout = new javax.swing.GroupLayout(Acadstab);
        Acadstab.setLayout(AcadstabLayout);
        AcadstabLayout.setHorizontalGroup(
            AcadstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AcadstabLayout.createSequentialGroup()
                .addGroup(AcadstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AcadstabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Coursepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Studentpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AcadstabLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(Evaluate, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AcadstabLayout.setVerticalGroup(
            AcadstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AcadstabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AcadstabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Coursepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Studentpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(Evaluate)
                .addGap(31, 31, 31))
        );

        jTabbedPane1.addTab("Academics", Acadstab);

        LocTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        LocTable.setColumnSelectionAllowed(true);
        LocTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(LocTable);
        LocTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (LocTable.getColumnModel().getColumnCount() > 0) {
            LocTable.getColumnModel().getColumn(0).setResizable(false);
            LocTable.getColumnModel().getColumn(1).setResizable(false);
        }

        AddItem.setText("Add Item");

        DelItem.setText("Delete Item");

        ModItem.setText("Modify Details");

        DispNum.setText("Display by Numbers");

        javax.swing.GroupLayout InventorytabLayout = new javax.swing.GroupLayout(Inventorytab);
        Inventorytab.setLayout(InventorytabLayout);
        InventorytabLayout.setHorizontalGroup(
            InventorytabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventorytabLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(InventorytabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(DelItem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DispNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddItem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        InventorytabLayout.setVerticalGroup(
            InventorytabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventorytabLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(AddItem)
                .addGap(18, 18, 18)
                .addComponent(DelItem)
                .addGap(18, 18, 18)
                .addComponent(ModItem)
                .addGap(29, 29, 29)
                .addComponent(DispNum)
                .addGap(63, 63, 63))
            .addGroup(InventorytabLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Inventory", Inventorytab);

        TransType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grant", "Fund", "Non Inventory Expenture" }));
        TransType.setToolTipText("Select a transaction type");
        TransType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransTypeActionPerformed(evt);
            }
        });

        jLabel4.setText("Transaction Type:");

        jLabel5.setText("Price:");

        PriceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceFieldActionPerformed(evt);
            }
        });

        DetailsArea.setColumns(20);
        DetailsArea.setRows(5);
        Details.setViewportView(DetailsArea);

        jLabel6.setText("Details:");

        AddTrans.setText("Add Transaction");

        javax.swing.GroupLayout TreasurytabLayout = new javax.swing.GroupLayout(Treasurytab);
        Treasurytab.setLayout(TreasurytabLayout);
        TreasurytabLayout.setHorizontalGroup(
            TreasurytabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TreasurytabLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(TreasurytabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(35, 35, 35)
                .addGroup(TreasurytabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddTrans)
                    .addComponent(Details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TreasurytabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TransType, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PriceField)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        TreasurytabLayout.setVerticalGroup(
            TreasurytabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TreasurytabLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(TreasurytabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TransType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TreasurytabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(PriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TreasurytabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(AddTrans)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Treasury", Treasurytab);

        Logspanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Logs"));

        jLabel10.setText("Debit");

        DebitsArea.setColumns(20);
        DebitsArea.setRows(5);
        jScrollPane4.setViewportView(DebitsArea);

        CreditsArea.setColumns(20);
        CreditsArea.setRows(5);
        jScrollPane5.setViewportView(CreditsArea);

        jLabel11.setText("Credit");

        javax.swing.GroupLayout LogspanelLayout = new javax.swing.GroupLayout(Logspanel);
        Logspanel.setLayout(LogspanelLayout);
        LogspanelLayout.setHorizontalGroup(
            LogspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogspanelLayout.createSequentialGroup()
                .addGroup(LogspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LogspanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel10))
                    .addGroup(LogspanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(LogspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogspanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogspanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(179, 179, 179))))
        );
        LogspanelLayout.setVerticalGroup(
            LogspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogspanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LogspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LogspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(jScrollPane5))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel7.setText("Income :");

        jLabel8.setText("Expenditure :");

        jLabel9.setText("Balance :");

        javax.swing.GroupLayout CashbooktabLayout = new javax.swing.GroupLayout(Cashbooktab);
        Cashbooktab.setLayout(CashbooktabLayout);
        CashbooktabLayout.setHorizontalGroup(
            CashbooktabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CashbooktabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logspanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(CashbooktabLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(CashbooktabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CashbooktabLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BalField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CashbooktabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(CashbooktabLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(ExpField))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CashbooktabLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(IncField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CashbooktabLayout.setVerticalGroup(
            CashbooktabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CashbooktabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CashbooktabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(IncField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CashbooktabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ExpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CashbooktabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(BalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Logspanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cash book", Cashbooktab);

        Respanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Research Projects"));

        ResArea.setColumns(20);
        ResArea.setRows(5);
        jScrollPane3.setViewportView(ResArea);

        javax.swing.GroupLayout RespanelLayout = new javax.swing.GroupLayout(Respanel);
        Respanel.setLayout(RespanelLayout);
        RespanelLayout.setHorizontalGroup(
            RespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RespanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        RespanelLayout.setVerticalGroup(
            RespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RespanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );

        Pubpanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Publications"));

        PubArea.setColumns(20);
        PubArea.setRows(5);
        jScrollPane6.setViewportView(PubArea);

        javax.swing.GroupLayout PubpanelLayout = new javax.swing.GroupLayout(Pubpanel);
        Pubpanel.setLayout(PubpanelLayout);
        PubpanelLayout.setHorizontalGroup(
            PubpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PubpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );
        PubpanelLayout.setVerticalGroup(
            PubpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PubpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6)
                .addContainerGap())
        );

        AddResPub.setText("Add New ");

        javax.swing.GroupLayout ResPubtabLayout = new javax.swing.GroupLayout(ResPubtab);
        ResPubtab.setLayout(ResPubtabLayout);
        ResPubtabLayout.setHorizontalGroup(
            ResPubtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResPubtabLayout.createSequentialGroup()
                .addGroup(ResPubtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ResPubtabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Respanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Pubpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ResPubtabLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(AddResPub, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ResPubtabLayout.setVerticalGroup(
            ResPubtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResPubtabLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(AddResPub)
                .addGap(18, 18, 18)
                .addGroup(ResPubtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Respanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pubpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Research/Publication", ResPubtab);

        SearchField.setText("Enter Search ");

        SearchResTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Author", "Expenditure", "Details"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(SearchResTable);
        if (SearchResTable.getColumnModel().getColumnCount() > 0) {
            SearchResTable.getColumnModel().getColumn(0).setResizable(false);
            SearchResTable.getColumnModel().getColumn(1).setResizable(false);
            SearchResTable.getColumnModel().getColumn(2).setResizable(false);
            SearchResTable.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout SearchtabLayout = new javax.swing.GroupLayout(Searchtab);
        Searchtab.setLayout(SearchtabLayout);
        SearchtabLayout.setHorizontalGroup(
            SearchtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchtabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SearchtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchField)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE))
                .addContainerGap())
        );
        SearchtabLayout.setVerticalGroup(
            SearchtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchtabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Search", Searchtab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String pwd = new String(this.jPasswordField1.getPassword());
                if (pwd.equals("admin")){                    
                    this.LoginPopup.setVisible(false);
                    this.setVisible(true);
                    Date d = new Date();
                    SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");
                    this.time.setText(sdf.format(d));
                    SimpleDateFormat sdf1 = new SimpleDateFormat("dd-MM-yyyy");
                    this.date.setText(sdf1.format(d));
                    this.sem.setText("Semester : Spring");
                }else{
                    this.LoginPwdError.setLocationRelativeTo(null);
                    this.LoginPwdError.setVisible(true);
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        String pwd = new String(this.jPasswordField1.getPassword());
                if (pwd.equals("admin")){                    
                    this.LoginPopup.setVisible(false);
                    this.setVisible(true);
                    Date d = new Date();
                    SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");
                    this.time.setText(sdf.format(d));
                    SimpleDateFormat sdf1 = new SimpleDateFormat("dd-MM-yyyy");
                    this.date.setText(sdf1.format(d));
                    this.sem.setText("Semester : Spring");
                }else{
                    this.LoginPwdError.setLocationRelativeTo(null);
                    this.LoginPwdError.setVisible(true);
                }
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void TransTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TransTypeActionPerformed

    private void AddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddCourseActionPerformed

    private void PriceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceFieldActionPerformed

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        this.LoginPwdError.setVisible(false);
    }//GEN-LAST:event_OKButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    //javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    String laf = javax.swing.UIManager.getSystemLookAndFeelClassName();
                    javax.swing.UIManager.setLookAndFeel(laf);
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                
                
                StartGUI s = new StartGUI();
                s.LoginPopup.setLocationRelativeTo(null);
                s.LoginPopup.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Acadstab;
    private javax.swing.JButton AddCourse;
    private javax.swing.JButton AddItem;
    private javax.swing.JButton AddResPub;
    private javax.swing.JButton AddTrans;
    private javax.swing.JTextField BalField;
    private javax.swing.JPanel Cashbooktab;
    private javax.swing.JPanel Coursepanel;
    private javax.swing.JTextArea CreditsArea;
    private javax.swing.JTextArea DebitsArea;
    private javax.swing.JButton DelCourse;
    private javax.swing.JButton DelItem;
    private javax.swing.JScrollPane Details;
    private javax.swing.JTextArea DetailsArea;
    private javax.swing.JButton DispNum;
    private javax.swing.JButton EnrollStudent;
    private javax.swing.JButton Evaluate;
    private javax.swing.JTextField ExpField;
    private javax.swing.JPanel Hometab;
    private javax.swing.JTextField IncField;
    private javax.swing.JPanel Inventorytab;
    private javax.swing.JTable LocTable;
    private javax.swing.JFrame LoginPopup;
    private javax.swing.JDialog LoginPwdError;
    private javax.swing.JPanel Logspanel;
    private javax.swing.JButton ModItem;
    private javax.swing.JButton NewStudent;
    private javax.swing.JButton OKButton;
    private javax.swing.JTextField PriceField;
    private javax.swing.JButton PrintStudent;
    private javax.swing.JTextArea PubArea;
    private javax.swing.JPanel Pubpanel;
    private javax.swing.JTextArea ResArea;
    private javax.swing.JPanel ResPubtab;
    private javax.swing.JPanel Respanel;
    private javax.swing.JTextField SearchField;
    private javax.swing.JTable SearchResTable;
    private javax.swing.JPanel Searchtab;
    private javax.swing.JPanel Studentpanel;
    private javax.swing.JComboBox<String> TransType;
    private javax.swing.JPanel Treasurytab;
    private javax.swing.JButton ViewCourse;
    private javax.swing.JLabel date;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel sem;
    private javax.swing.JLabel time;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
